### ISSUE TITLE
[Bug] Can't use in browser environment

### ISSUE THREAD

**Issue by Lippiece** [InvidJS/InvidJS#19]
### Describe the bug.

I'm using Vite, React, react-router. In a router loader, I call invidJS to fetch instances. Any function I tried, I receive the following errors.

### Code and Stack Trace

In a route loader:

```
import * as invidJS from "@invidjs/invid-js"
...
const instances = await invidJS.fetchInstances()
...
```

Errors in the devtools:
```
Module "stream" has been externalized for browser compatibility. Cannot access "stream.Stream" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.

browser-external:fs:9 Uncaught TypeError: Cannot convert a Symbol value to a string
  at Object.get (browser-external:fs:9:102)
    at node_modules/graceful-fs/graceful-fs.js (graceful-fs.js:43:6)
    at __require2 (chunk-OZI5HTJH.js?v=4f187028:15:50)
    at node_modules/@invidjs/invid-js/node_modules/fs-extra/lib/fs/index.js (index.js:5:12)
    at __require2 (chunk-OZI5HTJH.js?v=4f187028:15:50)
    at node_modules/@invidjs/invid-js/node_modules/fs-extra/lib/index.js (index.js:5:6)
    at __require2 (chunk-OZI5HTJH.js?v=4f187028:15:50)
    at index.mjs:222:16
get @ browser-external:fs:9
node_modules/graceful-fs/graceful-fs.js @ graceful-fs.js:43
__require2 @ chunk-OZI5HTJH.js?v=4f187028:15
node_modules/@invidjs/invid-js/node_modules/fs-extra/lib/fs/index.js @ index.js:5
__require2 @ chunk-OZI5HTJH.js?v=4f187028:15
node_modules/@invidjs/invid-js/node_modules/fs-extra/lib/index.js @ index.js:5
__require2 @ chunk-OZI5HTJH.js?v=4f187028:15
(anonymous) @ index.mjs:222
```  

### Expected behaviour

Fetch instances data.

### Additional context

https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility

**Comment by alexavil** [comment]
@Lippiece I attempted to rebuild the package using the stock `fs` package instead of `fs-extra`.
Can you install `@invidjs/invid-js-test` and find out if that fixes the issue?

**Comment by Lippiece** [comment]
> @Lippiece I attempted to rebuild the package using the stock `fs` package instead of `fs-extra`. Can you install `@invidjs/invid-js-test` and find out if that fixes the issue?
Yes, now it fetches data normally. Nice!

**Comment by alexavil** [comment]
I published the fix to npm. You may install the stable release now or keep using the bleeding edge version. Thanks for your feedback!
