### ISSUE TITLE
A lot of instances are dark

### ISSUE THREAD

**Issue by alexavil** [InvidJS/InvidJS#37]
Will need to allow the user to punch a custom URL, or come up with another solution.

**Comment by HeteroChromia420** [comment]
a Proposal: Come up with a way for InvidJS to, in case the default instance fails to connect, try a different instance from a list. try 4 different ones before giving up, maybe?

**Comment by alexavil** [comment]
Turns out to be an issue with Russian IPs. Invidious is not in an immediate danger.
