### ISSUE TITLE
[Bug] Cannot fetch instances

### ISSUE THREAD

**Issue by EgidioCaprino** [InvidJS/InvidJS#46]
### Describe the bug.

The `fetchInstances` method is broken

### Code and Stack Trace

```javascript
test("Only a single instance should be fetched if a URL is given.", async () => {
  const instances = await InvidJS.fetchInstances({
    url: "https://vid.puffyan.us",
  });
  expect(instances).toHaveLength(1);
  expect(instances[0].url).toBe("https://vid.puffyan.us");
}, 60000);
```

![image](https://github.com/InvidJS/InvidJS/assets/5156120/96a641af-9ece-4a71-8418-8bb21bff998b)

### Expected behaviour

Test cases should pass

**Comment by alexavil** [comment]
The new patch removes the Daily Health, which was responsible for this bug.
